export const BLOG_CREATE_REQUEST="BLOG_CREATE_REQUEST"
export const BLOG_CREATE_SUCCESS="BLOG_CREATE_SUCCESS"
export const BLOG_CREATE_FAIL="BLOG_CREATE_FAIL"

export const BLOGS_LIST_REQUEST="BLOGS_LIST_REQUEST"
export const BLOGS_LIST_SUCCESS="BLOGS_LIST_SUCCESS"
export const BLOGS_LIST_FAIL="BLOGS_LIST_FAIL"


export const BLOG_UPDATE_REQUEST="BLOG_UPDATE_REQUEST"
export const BLOG_UPDATE_SUCCESS="BLOG_UPDATE_SUCCESS"
export const BLOG_UPDATE_FAIL="BLOG_UPDATE_FAIL"


export const BLOG_DELETE_REQUEST="BLOG_DELETE_REQUEST"
export const BLOG_DELETE_SUCCESS="BLOG_DELETE_SUCCESS"
export const BLOG_DELETE_FAIL="BLOG_DELETE_FAIL"

export const BLOG_VIEW_REQUEST="BLOG_VIEW_REQUEST"
export const BLOG_VIEW_SUCCESS="BLOG_VIEW_SUCCESS"
export const BLOG_VIEW_FAIL="BLOG_VIEW_FAIL"

